# Generated by Django 5.0 on 2023-12-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('imge', models.ImageField(upload_to='uploads')),
                ('desc', models.TextField()),
            ],
        ),
    ]
