# Generated by Django 5.0 on 2024-01-02 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
    ]
