# Generated by Django 5.0.1 on 2024-03-06 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_rename_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='imge',
            new_name='image',
        ),
    ]
